/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package teste;

/**
 *
 * @author lucas
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuProdutos = new javax.swing.JMenu();
        itmCadastrar = new javax.swing.JMenuItem();
        itmAlterar = new javax.swing.JMenuItem();
        itmBuscar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itmExcluir = new javax.swing.JMenuItem();
        itmListar = new javax.swing.JMenuItem();
        mnuProdutos2 = new javax.swing.JMenu();
        itmCadastrar2 = new javax.swing.JMenuItem();
        itmAlterar2 = new javax.swing.JMenuItem();
        itmBuscar2 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        itmExcluir2 = new javax.swing.JMenuItem();
        itmListar2 = new javax.swing.JMenuItem();
        mnuProdutos1 = new javax.swing.JMenu();
        itmAlterar1 = new javax.swing.JMenuItem();
        itmBuscar1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        itmExcluir1 = new javax.swing.JMenuItem();
        itmListar1 = new javax.swing.JMenuItem();
        mnuProdutos3 = new javax.swing.JMenu();
        itmAlterar3 = new javax.swing.JMenuItem();
        itmBuscar3 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        itmExcluir3 = new javax.swing.JMenuItem();
        itmListar3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu");
        getContentPane().setLayout(null);

        mnuProdutos.setText("Estoque");

        itmCadastrar.setText("Cadastrar");
        itmCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarActionPerformed(evt);
            }
        });
        mnuProdutos.add(itmCadastrar);

        itmAlterar.setText("Alterar");
        itmAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarActionPerformed(evt);
            }
        });
        mnuProdutos.add(itmAlterar);

        itmBuscar.setText("Buscar");
        itmBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmBuscarActionPerformed(evt);
            }
        });
        mnuProdutos.add(itmBuscar);
        mnuProdutos.add(jSeparator1);

        itmExcluir.setText("Excluir");
        itmExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirActionPerformed(evt);
            }
        });
        mnuProdutos.add(itmExcluir);

        itmListar.setText("Listar");
        itmListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarActionPerformed(evt);
            }
        });
        mnuProdutos.add(itmListar);

        jMenuBar1.add(mnuProdutos);

        mnuProdutos2.setText("Clientes");

        itmCadastrar2.setText("Cadastrar");
        itmCadastrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrar2ActionPerformed(evt);
            }
        });
        mnuProdutos2.add(itmCadastrar2);

        itmAlterar2.setText("Alterar");
        itmAlterar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterar2ActionPerformed(evt);
            }
        });
        mnuProdutos2.add(itmAlterar2);

        itmBuscar2.setText("Buscar");
        itmBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmBuscar2ActionPerformed(evt);
            }
        });
        mnuProdutos2.add(itmBuscar2);
        mnuProdutos2.add(jSeparator3);

        itmExcluir2.setText("Excluir");
        itmExcluir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluir2ActionPerformed(evt);
            }
        });
        mnuProdutos2.add(itmExcluir2);

        itmListar2.setText("Listar");
        itmListar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListar2ActionPerformed(evt);
            }
        });
        mnuProdutos2.add(itmListar2);

        jMenuBar1.add(mnuProdutos2);

        mnuProdutos1.setText("Pedidos");

        itmAlterar1.setText("Alterar");
        itmAlterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterar1ActionPerformed(evt);
            }
        });
        mnuProdutos1.add(itmAlterar1);

        itmBuscar1.setText("Buscar");
        itmBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmBuscar1ActionPerformed(evt);
            }
        });
        mnuProdutos1.add(itmBuscar1);
        mnuProdutos1.add(jSeparator2);

        itmExcluir1.setText("Excluir");
        itmExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluir1ActionPerformed(evt);
            }
        });
        mnuProdutos1.add(itmExcluir1);

        itmListar1.setText("Listar");
        itmListar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListar1ActionPerformed(evt);
            }
        });
        mnuProdutos1.add(itmListar1);

        jMenuBar1.add(mnuProdutos1);

        mnuProdutos3.setText("Rastrear");

        itmAlterar3.setText("Alterar");
        itmAlterar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterar3ActionPerformed(evt);
            }
        });
        mnuProdutos3.add(itmAlterar3);

        itmBuscar3.setText("Buscar");
        itmBuscar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmBuscar3ActionPerformed(evt);
            }
        });
        mnuProdutos3.add(itmBuscar3);
        mnuProdutos3.add(jSeparator4);

        itmExcluir3.setText("Excluir");
        itmExcluir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluir3ActionPerformed(evt);
            }
        });
        mnuProdutos3.add(itmExcluir3);

        itmListar3.setText("Listar");
        itmListar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListar3ActionPerformed(evt);
            }
        });
        mnuProdutos3.add(itmListar3);

        jMenuBar1.add(mnuProdutos3);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(720, 402));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarActionPerformed
        new CadastrarProduto().setVisible(true);
    }//GEN-LAST:event_itmCadastrarActionPerformed

    private void itmAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarActionPerformed
        new AlterarProduto().setVisible(true);
    }//GEN-LAST:event_itmAlterarActionPerformed

    private void itmBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBuscarActionPerformed
        new BuscarProduto().setVisible(true);
    }//GEN-LAST:event_itmBuscarActionPerformed

    private void itmListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarActionPerformed
        new ListarProduto().setVisible(true);
    }//GEN-LAST:event_itmListarActionPerformed

    private void itmExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirActionPerformed
        new ExcluirProduto().setVisible(true);
    }//GEN-LAST:event_itmExcluirActionPerformed

    private void itmCadastrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmCadastrar2ActionPerformed

    private void itmAlterar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmAlterar2ActionPerformed

    private void itmBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBuscar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmBuscar2ActionPerformed

    private void itmExcluir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluir2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmExcluir2ActionPerformed

    private void itmListar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmListar2ActionPerformed

    private void itmAlterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmAlterar1ActionPerformed

    private void itmBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBuscar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmBuscar1ActionPerformed

    private void itmExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmExcluir1ActionPerformed

    private void itmListar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmListar1ActionPerformed

    private void itmAlterar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmAlterar3ActionPerformed

    private void itmBuscar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBuscar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmBuscar3ActionPerformed

    private void itmExcluir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluir3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmExcluir3ActionPerformed

    private void itmListar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmListar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAlterar;
    private javax.swing.JMenuItem itmAlterar1;
    private javax.swing.JMenuItem itmAlterar2;
    private javax.swing.JMenuItem itmAlterar3;
    private javax.swing.JMenuItem itmBuscar;
    private javax.swing.JMenuItem itmBuscar1;
    private javax.swing.JMenuItem itmBuscar2;
    private javax.swing.JMenuItem itmBuscar3;
    private javax.swing.JMenuItem itmCadastrar;
    private javax.swing.JMenuItem itmCadastrar2;
    private javax.swing.JMenuItem itmExcluir;
    private javax.swing.JMenuItem itmExcluir1;
    private javax.swing.JMenuItem itmExcluir2;
    private javax.swing.JMenuItem itmExcluir3;
    private javax.swing.JMenuItem itmListar;
    private javax.swing.JMenuItem itmListar1;
    private javax.swing.JMenuItem itmListar2;
    private javax.swing.JMenuItem itmListar3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenu mnuProdutos;
    private javax.swing.JMenu mnuProdutos1;
    private javax.swing.JMenu mnuProdutos2;
    private javax.swing.JMenu mnuProdutos3;
    // End of variables declaration//GEN-END:variables
}
