/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package teste;

/**
 *
 * @author lucas
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuProdutos = new javax.swing.JMenu();
        itmCadastrarProduto = new javax.swing.JMenuItem();
        itmAlterarProduto = new javax.swing.JMenuItem();
        itmBuscarProduto = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itmExcluirProduto = new javax.swing.JMenuItem();
        itmListarProduto = new javax.swing.JMenuItem();
        mnuProdutos2 = new javax.swing.JMenu();
        itmCadastrarCliente = new javax.swing.JMenuItem();
        itmAlterarCliente = new javax.swing.JMenuItem();
        itmBuscarCliente = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        itmExcluirCliente = new javax.swing.JMenuItem();
        itmListarCliente = new javax.swing.JMenuItem();
        mnuProdutos1 = new javax.swing.JMenu();
        itmAlterar1 = new javax.swing.JMenuItem();
        itmBuscar1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        itmExcluir1 = new javax.swing.JMenuItem();
        itmListar1 = new javax.swing.JMenuItem();
        mnuProdutos3 = new javax.swing.JMenu();
        itmAlterar3 = new javax.swing.JMenuItem();
        itmBuscar3 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        itmExcluir3 = new javax.swing.JMenuItem();
        itmListar3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu");
        getContentPane().setLayout(null);

        mnuProdutos.setText("Estoque");

        itmCadastrarProduto.setText("Cadastrar");
        itmCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarProdutoActionPerformed(evt);
            }
        });
        mnuProdutos.add(itmCadastrarProduto);

        itmAlterarProduto.setText("Alterar");
        itmAlterarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarProdutoActionPerformed(evt);
            }
        });
        mnuProdutos.add(itmAlterarProduto);

        itmBuscarProduto.setText("Buscar");
        itmBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmBuscarProdutoActionPerformed(evt);
            }
        });
        mnuProdutos.add(itmBuscarProduto);
        mnuProdutos.add(jSeparator1);

        itmExcluirProduto.setText("Excluir");
        itmExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirProdutoActionPerformed(evt);
            }
        });
        mnuProdutos.add(itmExcluirProduto);

        itmListarProduto.setText("Listar");
        itmListarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarProdutoActionPerformed(evt);
            }
        });
        mnuProdutos.add(itmListarProduto);

        jMenuBar1.add(mnuProdutos);

        mnuProdutos2.setText("Clientes");

        itmCadastrarCliente.setText("Cadastrar");
        itmCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarClienteActionPerformed(evt);
            }
        });
        mnuProdutos2.add(itmCadastrarCliente);

        itmAlterarCliente.setText("Alterar");
        itmAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarClienteActionPerformed(evt);
            }
        });
        mnuProdutos2.add(itmAlterarCliente);

        itmBuscarCliente.setText("Buscar");
        itmBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmBuscarClienteActionPerformed(evt);
            }
        });
        mnuProdutos2.add(itmBuscarCliente);
        mnuProdutos2.add(jSeparator3);

        itmExcluirCliente.setText("Excluir");
        itmExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirClienteActionPerformed(evt);
            }
        });
        mnuProdutos2.add(itmExcluirCliente);

        itmListarCliente.setText("Listar");
        itmListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarClienteActionPerformed(evt);
            }
        });
        mnuProdutos2.add(itmListarCliente);

        jMenuBar1.add(mnuProdutos2);

        mnuProdutos1.setText("Pedidos");

        itmAlterar1.setText("Alterar");
        itmAlterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterar1ActionPerformed(evt);
            }
        });
        mnuProdutos1.add(itmAlterar1);

        itmBuscar1.setText("Buscar");
        itmBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmBuscar1ActionPerformed(evt);
            }
        });
        mnuProdutos1.add(itmBuscar1);
        mnuProdutos1.add(jSeparator2);

        itmExcluir1.setText("Excluir");
        itmExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluir1ActionPerformed(evt);
            }
        });
        mnuProdutos1.add(itmExcluir1);

        itmListar1.setText("Listar");
        itmListar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListar1ActionPerformed(evt);
            }
        });
        mnuProdutos1.add(itmListar1);

        jMenuBar1.add(mnuProdutos1);

        mnuProdutos3.setText("Rastrear");

        itmAlterar3.setText("Alterar");
        itmAlterar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterar3ActionPerformed(evt);
            }
        });
        mnuProdutos3.add(itmAlterar3);

        itmBuscar3.setText("Buscar");
        itmBuscar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmBuscar3ActionPerformed(evt);
            }
        });
        mnuProdutos3.add(itmBuscar3);
        mnuProdutos3.add(jSeparator4);

        itmExcluir3.setText("Excluir");
        itmExcluir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluir3ActionPerformed(evt);
            }
        });
        mnuProdutos3.add(itmExcluir3);

        itmListar3.setText("Listar");
        itmListar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListar3ActionPerformed(evt);
            }
        });
        mnuProdutos3.add(itmListar3);

        jMenuBar1.add(mnuProdutos3);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(720, 402));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarProdutoActionPerformed
        new CadastrarProduto().setVisible(true);
    }//GEN-LAST:event_itmCadastrarProdutoActionPerformed

    private void itmAlterarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarProdutoActionPerformed
        new AlterarProduto().setVisible(true);
    }//GEN-LAST:event_itmAlterarProdutoActionPerformed

    private void itmBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBuscarProdutoActionPerformed
        new BuscarProduto().setVisible(true);
    }//GEN-LAST:event_itmBuscarProdutoActionPerformed

    private void itmListarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarProdutoActionPerformed
        new ListarProduto().setVisible(true);
    }//GEN-LAST:event_itmListarProdutoActionPerformed

    private void itmExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirProdutoActionPerformed
        new ExcluirProduto().setVisible(true);
    }//GEN-LAST:event_itmExcluirProdutoActionPerformed

    private void itmCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarClienteActionPerformed
        new CadastrarCliente().setVisible(true);
    }//GEN-LAST:event_itmCadastrarClienteActionPerformed

    private void itmAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarClienteActionPerformed
        new AlterarCliente().setVisible(true);
    }//GEN-LAST:event_itmAlterarClienteActionPerformed

    private void itmBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBuscarClienteActionPerformed
        new BuscarCliente().setVisible(true);
    }//GEN-LAST:event_itmBuscarClienteActionPerformed

    private void itmExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirClienteActionPerformed
        new ExcluirCliente().setVisible(true);
    }//GEN-LAST:event_itmExcluirClienteActionPerformed

    private void itmListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarClienteActionPerformed
        new ListarCliente().setVisible(true);
    }//GEN-LAST:event_itmListarClienteActionPerformed

    private void itmAlterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmAlterar1ActionPerformed

    private void itmBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBuscar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmBuscar1ActionPerformed

    private void itmExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmExcluir1ActionPerformed

    private void itmListar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmListar1ActionPerformed

    private void itmAlterar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmAlterar3ActionPerformed

    private void itmBuscar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBuscar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmBuscar3ActionPerformed

    private void itmExcluir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluir3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmExcluir3ActionPerformed

    private void itmListar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmListar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAlterar1;
    private javax.swing.JMenuItem itmAlterar3;
    private javax.swing.JMenuItem itmAlterarCliente;
    private javax.swing.JMenuItem itmAlterarProduto;
    private javax.swing.JMenuItem itmBuscar1;
    private javax.swing.JMenuItem itmBuscar3;
    private javax.swing.JMenuItem itmBuscarCliente;
    private javax.swing.JMenuItem itmBuscarProduto;
    private javax.swing.JMenuItem itmCadastrarCliente;
    private javax.swing.JMenuItem itmCadastrarProduto;
    private javax.swing.JMenuItem itmExcluir1;
    private javax.swing.JMenuItem itmExcluir3;
    private javax.swing.JMenuItem itmExcluirCliente;
    private javax.swing.JMenuItem itmExcluirProduto;
    private javax.swing.JMenuItem itmListar1;
    private javax.swing.JMenuItem itmListar3;
    private javax.swing.JMenuItem itmListarCliente;
    private javax.swing.JMenuItem itmListarProduto;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenu mnuProdutos;
    private javax.swing.JMenu mnuProdutos1;
    private javax.swing.JMenu mnuProdutos2;
    private javax.swing.JMenu mnuProdutos3;
    // End of variables declaration//GEN-END:variables
}
